import image1 from "../assets/guitars/1.png";
import image2 from "../assets/guitars/2.png";
import image3 from "../assets/guitars/3.png";
import image4 from "../assets/guitars/4.png";
import image5 from "../assets/guitars/5.png";
import image6 from "../assets/guitars/6.png";
import image7 from "../assets/guitars/7.png";
import image8 from "../assets/guitars/8.png";
import image9 from "../assets/guitars/9.png";
import image10 from "../assets/guitars/10.png";
import image11 from "../assets/guitars/11.png";
import image12 from "../assets/guitars/12.png";
import image13 from "../assets/accessories/1.png";
import image14 from "../assets/accessories/2.png";
import image15 from "../assets/accessories/3.png";
import image16 from "../assets/accessories/4.png";
import image17 from "../assets/accessories/5.png";
import image18 from "../assets/accessories/6.png";
import image19 from "../assets/accessories/7.png";
import image20 from "../assets/accessories/8.png";
import image21 from "../assets/accessories/9.png";
import image22 from "../assets/accessories/10.png";
import image23 from "../assets/accessories/11.png";
import image24 from "../assets/accessories/12.png";

const guitarData = [
  {
    serialNumber: "1",
    title: "Fender Strato",
    brandName: "Fender",
    modelName: "Strato",
    guitarType: "Electric",
    numberOfStrings: 4,
    prevPrice: 1999,
    price: 999,
    color: "Black",
    image: image1,
    material: "Plastic",
    quantity: 1,
  },
  {
    serialNumber: "2",
    title: "Gibson Les Paul",
    brandName: "Gibson",
    modelName: "Les Paul",
    guitarType: "Electric",
    numberOfStrings: 6,
    prevPrice: 3000,
    price: 1299,
    color: "Red",
    image: image2,
    material: "Plastic",
    quantity: 1,
  },
  {
    serialNumber: "3",
    title: "Taylor 314ce",
    brandName: "Taylor",
    modelName: "314ce",
    guitarType: "Acoustic",
    numberOfStrings: 6,
    prevPrice: 3000,
    price: 1499,
    color: "Brown",
    image: image3,
    material: "Wooden",
    quantity: 1,
  },
  {
    serialNumber: "4",
    title: "Ibanez RG550",
    brandName: "Ibanez",
    modelName: "RG550",
    guitarType: "Electric",
    numberOfStrings: 6,
    prevPrice: 1500,
    price: 899,
    color: "Red",
    image: image4,
    material: "Plastic",
    quantity: 1,
  },
  {
    serialNumber: "5",
    title: "Martin D-28",
    brandName: "Martin",
    modelName: "D-28",
    guitarType: "Acoustic",
    numberOfStrings: 6,
    prevPrice: 2500,
    price: 1799,
    color: "Brown",
    image: image5,
    material: "Wooden",
    quantity: 1,
  },
  {
    serialNumber: "6",
    title: "PRS Custom 24",
    brandName: "PRS",
    modelName: "Custom 24",
    guitarType: "Electric",
    numberOfStrings: 6,
    prevPrice: 2399,
    price: 1599,
    color: "Brown",
    image: image6,
    material: "Plastic",
    quantity: 1,
  },
  {
    serialNumber: "7",
    title: "Gretsch G26622",
    brandName: "Gretsch",
    modelName: "G2622",
    guitarType: "Electric",
    numberOfStrings: 6,
    prevPrice: 1499,
    price: 699,
    color: "Blue",
    image: image7,
    material: "Plastic",
    quantity: 1,
  },
  {
    serialNumber: "8",
    title: "Epiphone Les Paul",
    brandName: "Epiphone",
    modelName: "Les Paul",
    guitarType: "Electric",
    numberOfStrings: 6,
    prevPrice: 1099,
    price: 499,
    color: "Red",
    image: image8,
    material: "Plastic",
    quantity: 1,
  },
  {
    serialNumber: "9",
    title: "Yamaha 112V",
    brandName: "Yamaha",
    modelName: "112V",
    guitarType: "Electric",
    numberOfStrings: 6,
    prevPrice: 599,
    price: 299,
    color: "Red",
    image: image9,
    material: "Plastic",
    quantity: 1,
  },
  {
    serialNumber: "10",
    title: "Gibson SG",
    brandName: "Gibson",
    modelName: "SG",
    guitarType: "Electric",
    numberOfStrings: 6,
    prevPrice: 2099,
    price: 1199,
    color: "Blue",
    image: image10,
    material: "Plastic",
    quantity: 1,
  },
  {
    serialNumber: "11",
    title: "Taylor 214ce",
    brandName: "Taylor",
    modelName: "214ce",
    guitarType: "Acoustic",
    numberOfStrings: 6,
    prevPrice: 1599,
    price: 1000,
    color: "Brown",
    image: image11,
    material: "Wooden",
    quantity: 1,
  },
  {
    serialNumber: "12",
    title: "Martin OM-28",
    brandName: "Martin",
    modelName: "OM-28",
    guitarType: "Acoustic",
    numberOfStrings: 6,
    prevPrice: 3099,
    price: 2299,
    color: "Brown",
    image: image12,
    material: "Wooden",
    quantity: 1,
  },
  {
    serialNumber: "13",
    title: "Fender Pick",
    brandName: "Fender",
    modelName: "FP-011",
    guitarType: "Electric",
    numberOfStrings: 3,
    prevPrice: 100,
    price: 50,
    color: "Brown",
    image: image13,
    material: "Plastic",
    quantity: 1,
  },
  {
    serialNumber: "14",
    title: "Gibson Pick",
    brandName: "Gibson",
    modelName: "GP-L24",
    guitarType: "Electric",
    numberOfStrings: 3,
    prevPrice: 100,
    price: 50,
    color: "Black",
    image: image14,
    material: "Plastic",
    quantity: 1,
  },
  {
    serialNumber: "15",
    title: "Taylor Pick",
    brandName: "Taylor",
    modelName: "TP-314ce",
    guitarType: "Acoustic",
    numberOfStrings: 3,
    prevPrice: 100,
    price: 50,
    color: "Red",
    image: image15,
    material: "Wooden",
    quantity: 1,
  },
  {
    serialNumber: "16",
    title: "Ibanez Pick",
    brandName: "Ibanez",
    modelName: "IP-RG550",
    guitarType: "Electric",
    numberOfStrings: 3,
    prevPrice: 100,
    price: 50,
    color: "Blue",
    image: image16,
    material: "Plastic",
    quantity: 1,
  },
  {
    serialNumber: "17",
    title: "Martin Pick",
    brandName: "Martin",
    modelName: "MPD-28",
    guitarType: "Acoustic",
    numberOfStrings: 3,
    prevPrice: 100,
    price: 50,
    color: "Black",
    image: image17,
    material: "Wooden",
    quantity: 1,
  },
  {
    serialNumber: "18",
    title: "PRS Pick",
    brandName: "PRS",
    modelName: "PRS-C-24",
    guitarType: "Electric",
    numberOfStrings: 3,
    prevPrice: 100,
    price: 50,
    color: "Red",
    image: image18,
    material: "Plastic",
    quantity: 1,
  },
  {
    serialNumber: "19",
    title: "Gretsch Pick",
    brandName: "Gretsch",
    modelName: "GP-2622",
    guitarType: "Electric",
    numberOfStrings: 3,
    prevPrice: 100,
    price: 50,
    color: "Blue",
    image: image19,
    material: "Plastic",
    quantity: 1,
  },
  {
    serialNumber: "20",
    title: "Epiphone Pick",
    brandName: "Epiphone",
    modelName: "EP-2424",
    guitarType: "Electric",
    numberOfStrings: 3,
    prevPrice: 100,
    price: 50,
    color: "Brown",
    image: image20,
    material: "Plastic",
    quantity: 1,
  },
  {
    serialNumber: "21",
    title: "Yamaha Strap",
    brandName: "Yamaha",
    modelName: "YS-112V",
    guitarType: "Electric",
    numberOfStrings: 1,
    prevPrice: 500,
    price: 150,
    color: "Blue",
    image: image21,
    material: "Leather",
    quantity: 1,
  },
  {
    serialNumber: "22",
    title: "Gibson Strap",
    brandName: "Gibson",
    modelName: "GS-SG22",
    guitarType: "Electric",
    numberOfStrings: 1,
    prevPrice: 500,
    price: 150,
    color: "Black",
    image: image22,
    material: "Leather",
    quantity: 1,
  },
  {
    serialNumber: "23",
    title: "Taylor Strap",
    brandName: "Taylor",
    modelName: "TS-214ce",
    guitarType: "Acoustic",
    numberOfStrings: 1,
    prevPrice: 500,
    price: 150,
    color: "Brown",
    image: image23,
    material: "Leather",
    quantity: 1,
  },
  {
    serialNumber: "24",
    title: "Martin Strap",
    brandName: "Martin",
    modelName: "MS-OM28",
    guitarType: "Acoustic",
    numberOfStrings: 1,
    prevPrice: 500,
    price: 150,
    color: "Red",
    image: image24,
    material: "Leather",
    quantity: 1,
  },
];

export default guitarData;
